version: '3'

services:
  mysql.monolito:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: eats
    volumes:
      - mysql.eats.monolito:/var/lib/mysql
  mysql.pagamento:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: eats_pagamento
      MYSQL_USER: pagamento
      MYSQL_PASSWORD: pagamento123
    volumes:
      - mysql.eats.pagamento:/var/lib/mysql
  mongo.distancia:
    image: mongo:3.6
    ports:
      - "27018:27017"
    volumes:
      - mongo.eats.distancia:/data/db
  
volumes:
  mysql.eats.monolito:
  mysql.eats.pagamento:
  mongo.eats.distancia:
